export const Data = {
  snapshot: {
    meta: {
      views: [
        {
          id: 'viwVv73VNxuLx',
          name: 'Grid view',
          rows: [{ recordId: 'recDitp5bdl8k' }],
          type: 1,
          columns: [
            { width: 247, fieldId: 'fldJQeiQX3sDA', statType: 1 },
            { hidden: false, fieldId: 'fldssFaH08Vx0', statType: 8 },
            { hidden: false, fieldId: 'fldopDApjrqlJ' },
            { hidden: false, fieldId: 'fldZRNG7tOB7v' },
            { hidden: false, fieldId: 'fld3aSUEHSwB8' },
            { hidden: false, fieldId: 'fldtvjUi0LYac' },
            { hidden: false, fieldId: 'fld18fEJGYLux' },
            { hidden: false, fieldId: 'fldeYy22ELsic' },
          ],
          autoSave: false,
          autoHeadHeight: false,
          rowHeightLevel: 1,
          frozenColumnCount: 1,
        },
        {
          id: 'viw2ccwuasvct',
          name: 'Gallery',
          rows: [{ recordId: 'recDitp5bdl8k' }],
          type: 3,
          style: { cardCount: 5, isCoverFit: false, layoutType: 'flex', isAutoLayout: false, isColNameVisible: true },
          columns: [
            { fieldId: 'fldJQeiQX3sDA', statType: 1 },
            { hidden: false, fieldId: 'fld18fEJGYLux' },
            { hidden: false, fieldId: 'fldtvjUi0LYac' },
            { hidden: false, fieldId: 'fld3aSUEHSwB8' },
            { hidden: false, fieldId: 'fldZRNG7tOB7v' },
            { hidden: false, fieldId: 'fldopDApjrqlJ' },
            { hidden: false, fieldId: 'fldssFaH08Vx0' },
            { hidden: false, fieldId: 'fldeYy22ELsic' },
          ],
        },
      ],
      fieldMap: {
        fld18fEJGYLux: { id: 'fld18fEJGYLux', name: 'Field 7', type: 1, property: null },
        fld3aSUEHSwB8: { id: 'fld3aSUEHSwB8', name: 'Field 5', type: 1, property: null },
        fldJQeiQX3sDA: { id: 'fldJQeiQX3sDA', name: 'Title', type: 19, property: { defaultValue: '' }},
        fldZRNG7tOB7v: { id: 'fldZRNG7tOB7v', name: 'Field 4', type: 1, property: null },
        fldeYy22ELsic: { id: 'fldeYy22ELsic', name: 'Test', type: 1, property: null },
        fldopDApjrqlJ: { id: 'fldopDApjrqlJ', name: 'Field 2', type: 1, property: null },
        fldssFaH08Vx0: { id: 'fldssFaH08Vx0', name: 'Field 1', type: 2, property: { precision: 1, commaStyle: ',', symbolAlign: 2 }},
        fldtvjUi0LYac: { id: 'fldtvjUi0LYac', name: 'Field 6', type: 1, property: null },
      },
    },
    recordMap: {
      recDitp5bdl8k: {
        id: 'recDitp5bdl8k',
        data: {
          fld18fEJGYLux: [{ text: '-6.9', type: 1 }],
          fld3aSUEHSwB8: [{ text: '7', type: 1 }],
          fldJQeiQX3sDA: [{ text: 'CC(=O)[C@H](C)CCNc1cc(NC(=O)c2c(Cl)cccc2Cl)ccn1', type: 1 }],
          fldZRNG7tOB7v: [{ text: '2', type: 1 }],
          fldopDApjrqlJ: [{ text: '4.66780', type: 1 }],
          fldssFaH08Vx0: 380.275,
          fldtvjUi0LYac: [{ text: '-8.30326', type: 1 }],
        },
        createdAt: 1676619358000,
        updatedAt: 1681118025000,
        revisionHistory: [80, 86, 112, 114, 120, 161, 166, 167],
        recordMeta: {
          createdAt: 1676619358106,
          createdBy: '938b52bc699043fc9923c8d5fe9999e9',
          fieldUpdatedMap: {
            fld18fEJGYLux: { at: 1676619982601, by: '938b52bc699043fc9923c8d5fe9999e9' },
            fld3aSUEHSwB8: { at: 1676619982601, by: '938b52bc699043fc9923c8d5fe9999e9' },
            fldJQeiQX3sDA: { at: 1676619982601, by: '938b52bc699043fc9923c8d5fe9999e9' },
            fldUDvz9KthtW: { at: 1676876525809, by: '938b52bc699043fc9923c8d5fe9999e9' },
            fldZRNG7tOB7v: { at: 1676619982601, by: '938b52bc699043fc9923c8d5fe9999e9' },
            fldopDApjrqlJ: { at: 1676619982601, by: '938b52bc699043fc9923c8d5fe9999e9' },
            fldssFaH08Vx0: { at: 1676623618473, by: '938b52bc699043fc9923c8d5fe9999e9' },
            fldtvjUi0LYac: { at: 1676619982601, by: '938b52bc699043fc9923c8d5fe9999e9' },
          },
        },
        commentCount: 0,
      },
    },
    datasheetId: 'dst8i3lmTos2lkfMFS',
  },
  datasheet: {
    id: 'dst8i3lmTos2lkfMFS',
    name: 'Tongfu',
    description: '{}',
    parentId: 'fodqKZch5MKiX',
    icon: '',
    nodeShared: false,
    nodePermitSet: false,
    revision: 167,
    spaceId: 'spcdfg2ZUgp5X',
    role: 'manager',
    permissions: {
      nodeId: 'dst8i3lmTos2lkfMFS',
      datasheetId: 'dst8i3lmTos2lkfMFS',
      manageable: true,
      editable: true,
      readable: true,
      childCreatable: true,
      renamable: true,
      iconEditable: true,
      descriptionEditable: true,
      movable: true,
      copyable: true,
      importable: true,
      exportable: true,
      removable: true,
      sharable: true,
      allowSaveConfigurable: true,
      allowEditConfigurable: true,
      templateCreatable: true,
      viewCreatable: true,
      viewRenamable: true,
      viewRemovable: true,
      viewMovable: true,
      viewExportable: true,
      viewFilterable: true,
      columnSortable: true,
      columnHideable: true,
      fieldSortable: true,
      fieldGroupable: true,
      rowHighEditable: true,
      columnWidthEditable: true,
      columnCountEditable: true,
      rowSortable: true,
      fieldCreatable: true,
      fieldRenamable: true,
      fieldPropertyEditable: true,
      fieldRemovable: true,
      rowCreatable: true,
      rowRemovable: true,
      cellEditable: true,
      fieldPermissionManageable: true,
      viewLayoutEditable: true,
      viewStyleEditable: true,
      viewKeyFieldEditable: true,
      viewColorOptionEditable: true,
      viewLockManageable: true,
      viewManualSaveManageable: true,
      viewOptionSaveEditable: true,
      isDeleted: false,
    },
    nodeFavorite: false,
    extra: { showRecordHistory: true },
    isGhostNode: false,
  },
  foreignDatasheetMap: {},
};
